# Generated by Django 5.2.16 on 2026-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_provider_sync_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='provider_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='thematic_area',
            field=models.CharField(db_index=True, default='Multidisciplinary / Unclassified', max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='thematic_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='thematic_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
